### ISSUE TITLE
[Feature request] Allow a set delay for opening each tab

### ISSUE THREAD

**Issue by rieje** [moritz-h/urls-list#11]
Feature request--allow a set delay for opening each tab (preferably implemented in a way where you can paste a list of URLs, then set a number like 500 milliseconds (something arbitary--not sure what a good duration is), then click "open" and it will open one tab at a time with a 500 milliseconds between each tab.

My use-case was a URL list containing the xda-developers.com site--it gave an error for most of the pages:

> 429 Rate Limited

> Whoa there, hold your horses! We've detected a lot of requests coming from your IP and have rate limited you. Please check your configuration and try again.

So I would have to go to those pages and manually refresh them to see the correct page. 

I'm not sure how many sites have such limitations, so if it's not too much of a niche case then it would be quite useful.

**Comment by moritz-h** [comment]
I think this would be not a nice solution. Waiting 500ms sounds very long (at least when you want to open more than 5 tabs at once).
This is a very rare case i think and adding an option for this in the opening dialog would make UI a lot more complicated.

By thinking of i nicer solution i thought about somehow opening the tabs inactive and then loading them when the tab becomes active. Unfortunately it seems that this is not possible with the Webextension API for tabs (at least for now).
But I found an other extension for doing this: https://addons.mozilla.org/en-US/firefox/addon/holdtab/
I tried to run it with the urls list extension, so it would suggest installing this extension.
(I would consider adding an option for this in future, if the tabs API would have an option to create load on demand tabs, but for now i think using the other extension makes more sense, than implementing the same thing here again)
I close this issue now, but please feel free to comment if you think otherwise.
