### ISSUE TITLE
Opening more than 2 URLs

### ISSUE THREAD

**Issue by crssi** [moritz-h/urls-list#16]
When I paste more than 2 URLs and hit open then just first 2 URLs are opened and I need to continue to hit open button until all URLs are opened.

Is this a desired situation or limitation of FF?

Cheers

**Comment by moritz-h** [comment]
No, all tabs should open. This sounds like a bug. I tested again with 20+ tabs, no problem for me. Can you please give more information? (Operating system, Firefox version, example URLs)

 The only limitation I build in is that an already opened URL is not opened again. All URLs that match exactly to an already opened tab are excluded, all other tabs should open.
(This is, that you can just extend the list with new URLs and the already opened URLs which are also listed in the box, are not opened again.)

**Comment by crssi** [comment]
Hi... tested it again against clean profile and it works.
Then I have narrowed down the conflicting addon, I am using, [Close Unused Blank Tabs](https://addons.mozilla.org/en-US/firefox/addon/close-unused-blank-tabs/).

But for example [Close Unused Blank Tabs](https://addons.mozilla.org/en-US/firefox/addon/close-unused-blank-tabs/) does not conflict with addon [Tab Session Manager](https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/) which can normally open a lot of tabs.

Cheers

**Comment by moritz-h** [comment]
I'm just using the official API to open an new tab with the given url:
`browser.tabs.create({url: url});`
This is the most simple case, see Mozilla Documentation: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create

There is not much I can change therefore this would be an issue of Close Unused Blank Tabs.
It seems that Tab Session Manager does configure a lot more options. Perhaps this does workaround the issue of Close Unused Blank Tabs.
But when Close Unused Blank Tabs breaks with the most simple case documented by Mozilla to open a new tab, it is most likely that the bug is there.

**Comment by crssi** [comment]
Perhaps it is or it is not.
I am just saying that the author of "Tab Session Manager" found the right procedure for this to work.
Maybe you can peek into his code and make your product even better and bullet prof against some other addon breakage. ;)

Cheers

**Comment by moritz-h** [comment]
@crssi I think that "Tab Session Manager" does not have this issue is more or less random and the problem is caused by "Close unused tabs".

I like to keep things as simple as possible. This is normally the most stable approach for any kind of problems. The most simple approach to create a new tab is calling `browser.tabs.create({url: 'some-url-to-open'});`. As documented by Mozilla! Therefore I do not think changing this will improve anything.

I installed "Close tabs" and I don't have any problems. Can you please test if there is not any third AddOn involved? (Fresh profile with just this AddOn and "Close Tabs")

I can just guess where this problem comes from. I read also the source of "Close Tabs". There is a event listener to tab creation. Then empty tabs are filtered and directly closed. Perhaps this is some race condition within Firefox between create tab => fire event => close empty tab => load content to tab. But I don't know anything about Firefox internals, I can only guess.
I cannot do anything else than use the normal tab creation API.

Please also report this to the "Close Tabs" AddOn.

**Comment by moritz-h** [comment]
If this really is a race condition (I can only guess) it has nothing to with installation order. This would be Firefox internals on execution. Only the solution would be then that "Clean Tabs" should add a short delay before closing tabs.

I'm using Firefox 57.0.1 on Ubuntu 16.04

**Comment by crssi** [comment]
Thank you. Will report to "Clean Tabs" author.

Cheers and thank you for your nice addon.
